In [34]:
#numpy Numerical Python
import numpy as np

In [6]:
Distance = [1000,5000,400,200]
dist = np.array(Distance)

In [3]:
type(dist)

numpy.ndarray

In [4]:
time = [100,200,30,50]
tim = np.array(time)

In [7]:
speed = dist/tim

In [8]:
speed

array([10.        , 25.        , 13.33333333,  4.        ])

In [9]:
dist.dtype #AUTO TYPE CONVERSION AND GETS THE

dtype('int64')

In [10]:
a= np.array([1,2,"aman",4.7])

In [11]:
a.dtype

dtype('<U21')

In [14]:
a.ndim

1

In [16]:
a.shape

(4,)

In [17]:
a.size

4

In [18]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
b[1:,2:]

array([[6],
       [9]])

In [21]:
ar = np.array([[[1,2,3,],[4,5,6],[7,8,9]],
              [[10,11,12],[13,14,15],[16,17,18]],
              [[19,20,21],[22,23,24],[25,26,27]]])

In [22]:
ar[:,1,1]

array([ 5, 14, 23])

In [23]:
ar

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [24]:
ar[1:2:3]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [38]:
b=[1,2,3,4,5,6,7,8,9]
bs = np.arange(1,10,2)
bs


array([1, 3, 5, 7, 9])

In [35]:
np.full((2,3),6)

array([[6, 6, 6],
       [6, 6, 6]])

In [41]:
np.ones((3,2))
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.random.random((3,2,3))

array([[[0.6416743 , 0.15213406, 0.01527928],
        [0.6327797 , 0.94341763, 0.03046853]],

       [[0.65098301, 0.70032655, 0.61311714],
        [0.47130854, 0.38910241, 0.65542697]],

       [[0.07961489, 0.78886602, 0.20061008],
        [0.98806854, 0.8185907 , 0.07139439]]])

In [46]:
age = np.random.randint(10,100,110)

In [45]:
from scipy import stats

In [47]:
stats.mode(age)

ModeResult(mode=array([63]), count=array([5]))

In [48]:
np.mean(age)

54.56363636363636

In [49]:
np.median(age)

55.5

In [50]:
np.std(age)

24.18621969511763

In [51]:
np.var(age)

584.9732231404959

In [52]:
24.18621969511763 * 24.18621969511763 # sd is sqrt of varience

584.9732231404959

In [53]:
ar12 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [55]:
np.mean(ar12,axis=1) # row axis is 1 here 

array([2., 5., 8.])

In [56]:
np.mean(ar12,axis=0) # coloumn is 0 here

array([4., 5., 6.])